# Dependencies
markdown:         kramdown 
highlighter:      rouge 

# Permalinks
permalink:        /:categories/:title/ 

# Setup
title:            Blog 
description:      'Another tech blog with functional flavored code and other ingredients.'
url:              https://gtrefs.github.io
baseurl:          /

author:
  name:           'Gregor Trefs'
  url:            https://twitter.com/gtrefs

disqus_shortname: gtrefs

paginate:         5
kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  syntax_highlighter: rouge

# Custom vars
version:          2.1.0
gems:
        - jekyll-sitemap
        - jekyll-paginate
        - jekyll-gist
        - jekyll-feed

github:
  repo:           https://github.com/gtrefs
